language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com" > .git/credentials
- npm run gulp preBuild
after_script:
- npm run gulp postBuild
branches:
  only:
    - master
    - es6-dev